[32mINFO    [0m integration.test_tls:test_tls.py:126 Relating TLS with mysqlrouter
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.test_tls:test_tls.py:129 Getting certificate issuer after relating with tls operator
[32mINFO    [0m integration.test_tls:test_tls.py:146 Removing relation TLS with mysqlrouter
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.2    unsupported  01:39:41Z

App                       Version                  Status  Scale  Charm                     Channel        Rev  Address         Exposed  Message
mysql-k8s                 8.0.41-0ubuntu0.22.04.1  active      1  mysql-k8s                 8.0/edge       232  10.152.183.64   no       
mysql-router-k8s          8.0.41-0ubuntu0.22.04.1  active      1  mysql-router-k8s                           0  10.152.183.215  no       
mysql-test-app            0.0.2                    active      1  mysql-test-app            latest/edge     63  10.152.183.175  no       Last written value=1120
self-signed-certificates                           active      1  self-signed-certificates  latest/stable  155  10.152.183.246  no       

Unit                         Workload  Agent      Address       Ports  Message
mysql-k8s/0*                 active    idle       10.1.105.203         Primary
mysql-router-k8s/0*          active    executing  10.1.105.205         (start) 
mysql-test-app/0*            active    idle       10.1.105.202         Last written value=1120
self-signed-certificates/0*  active    idle       10.1.105.204         

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-mysql-router-k8s-0: 01:39:37 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "70062993-af8a-4853-8e12-60eaa97a360f:r#9#self-signed-certificates": settings 70062993-af8a-4853-8e12-60eaa97a360f:r#9#self-signed-certificates not found (not found)

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...