[32mINFO    [0m pytest_operator.plugin:plugin.py:734 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:63 Deploying all the applications
[32mINFO    [0m juju.model:model.py:2097 Deploying ch:amd64/jammy/mysql-test-app-46
[32mINFO    [0m juju.model:model.py:2097 Deploying ch:amd64/jammy/grafana-agent-k8s-45
[32mINFO    [0m juju.model:model.py:2097 Deploying ch:amd64/jammy/mysql-k8s-180
[32mINFO    [0m juju.model:model.py:2097 Deploying local:jammy/mysql-router-k8s-0
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:100 Waiting for mysqlrouter to be in BlockedStatus
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:106 Relating mysql, mysqlrouter and application
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  mysql-router-k8s/0 [executing] waiting: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-router-k8s/0 [idle] active: 
  mysql-test-app/0 [idle] active: 
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:138 Deploying self-signed-certificates
[32mINFO    [0m juju.model:model.py:2097 Deploying ch:amd64/jammy/self-signed-certificates-155
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  self-signed-certificates/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  self-signed-certificates/0 [idle] active: 
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:149 Relating mysqlrouter with self-signed-certificates
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:172 Relating mysqlrouter with grafana agent
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1563 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:213 Removing relation between mysqlrouter and grafana agent
[32mINFO    [0m integration.test_exporter_with_tls:test_exporter_with_tls.py:233 Removing relation between mysqlrouter and self-signed-certificates
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.3    unsupported  01:39:40Z

App                       Version                  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
grafana-agent-k8s         0.32.1                   waiting      1  grafana-agent-k8s         latest/stable   45  10.152.183.173  no       installing agent
mysql-k8s                 8.0.37-0ubuntu0.22.04.3  active       1  mysql-k8s                 8.0/edge       180  10.152.183.168  no       
mysql-router-k8s          8.0.37-0ubuntu0.22.04.3  active       1  mysql-router-k8s                           0  10.152.183.194  no       
mysql-test-app            0.0.2                    active       1  mysql-test-app            latest/edge     46  10.152.183.224  no       
self-signed-certificates                           active       1  self-signed-certificates  latest/stable  155  10.152.183.210  no       

Unit                         Workload  Agent  Address     Ports  Message
grafana-agent-k8s/0*         blocked   idle   10.1.14.76         grafana-dashboards-provider: off, grafana-cloud-config: off
mysql-k8s/0*                 active    idle   10.1.14.77         Primary
mysql-router-k8s/0*          active    idle   10.1.14.72         
mysql-test-app/0*            active    idle   10.1.14.73         
self-signed-certificates/0*  active    idle   10.1.14.78         

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-mysql-k8s-0: 01:36:57 ERROR unit.mysql-k8s/0.juju-log upgrade:3: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/./src/charm.py", line 888, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 724, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/upgrade.py", line 206, in _on_upgrade_changed
    if not self.upgrade_stack and self.idle and self.charm.unit_initialized:
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 642, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 724, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 1539, in cluster_metadata_exists
    output = self._run_mysqlsh_script("\n".join(check_cluster_metadata_commands))
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 724, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 599, in _run_mysqlsh_script
    self.container.push(path=MYSQLSH_SCRIPT_FILE, source=script)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/model.py", line 2438, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2494, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/pebble.py", line 2048, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mysql/pebble.socket' (container restarted?)
unit-mysql-k8s-0: 01:36:57 ERROR juju.worker.uniter.operation hook "upgrade-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...